In [4]:
import pandas as pd
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as lda
from sklearn.model_selection import train_test_split
from sklearn.qda import QDA
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis as qda


In [5]:
df = pd.read_excel("Default.xlsx")


In [13]:
df["student"] = df["student"].astype('category')
df["student_cat"] = df["student"].cat.codes
df["default"] = df["default"].astype('category')
df["default_cat"] = df["default"].cat.codes

In [14]:

df = df.drop(["default","student"],axis = 1)

In [15]:
y = df["default_cat"]
df

balance        income  student_cat  default_cat
1       729.526495  44361.625074            0            0
2       817.180407  12106.134700            1            0
3      1073.549164  31767.138947            0            0
4       529.250605  35704.493935            0            0
5       785.655883  38463.495879            0            0
6       919.588530   7491.558572            1            0
7       825.513331  24905.226578            0            0
8       808.667504  17600.451344            1            0
9      1161.057854  37468.529288            0            0
10        0.000000  29275.268293            0            0
11        0.000000  21871.073089            1            0
12     1220.583753  13268.562221            1            0
13      237.045114  28251.695345            0            0
14      606.742343  44994.555849            0            0
15     1112.968401  23810.174050            0            0
16      286.232560  45042.413036            0            0
17        0.000000  50265.312354            0            0
18      527.540184  17636.539617            1            0
19      485.936864  61566.106118            0            0
20     1095.072735  26464.631389            0            0
21      228.952550  50500.182198            0            0
22      954.261793  32457.509075            0            0
23     1055.956605  51317.883082            0            0
24      641.984389  30466.103257            0            0
25      773.211725  34353.314305            0            0
26      855.008523  25211.332161            0            0
27      642.999739  41473.511801            0            0
28     1454.863272  32189.094952            0            0
29      615.704277  39376.394619            0            0
30     1119.569353  16556.070205            1            0
...            ...           ...          ...          ...
9971   1294.500408  25687.326050            1            0
9972    180.620128  20975.560495            1            0
9973    755.432801  14455.865365            0            0
9974    876.119027  37668.366788            0            0
9975    933.332025  26051.398320            1            0
9976    908.315934  21287.942487            0            0
9977    218.417559  25401.133121            0            0
9978    915.439827  16624.339111            1            0
9979   2202.462395  47287.257108            0            1
9980    173.249172  30697.245062            0            0
9981    770.015741  13684.789952            1            0
9982    739.418018  40656.951448            0            0
9983    623.526119  59441.309981            0            0
9984    506.625454  49861.003411            0            0
9985    875.241640  52861.744197            0            0
9986    842.949429  39957.127855            0            0
9987    401.332674  15332.017833            1            0
9988   1092.906583  45479.466985            0            0
9989      0.000000  41740.686597            0            0
9990    999.281112  20013.350644            1            0
9991    372.379239  25374.899085            0            0
9992    658.799558  54802.078221            0            0
9993   1111.647317  45490.682463            0            0
9994    938.836241  56633.448744            0            0
9995    172.412987  14955.941689            1            0
9996    711.555020  52992.378914            0            0
9997    757.962918  19660.721768            0            0
9998    845.411989  58636.156984            0            0
9999   1569.009053  36669.112365            0            0
10000   200.922183  16862.952321            1            0

[10000 rows x 4 columns]

In [16]:
df= df.drop(["default_cat"],axis = 1)


In [17]:
x_train,x_test,y_train,y_test = train_test_split(df,y,test_size = 0.2)

In [18]:
gnb = GaussianNB()
gnb.fit(x_train,y_train)
predictions_nb = gnb.predict(x_train)


In [25]:
clf = lda()#store_covariance=True
X_r2  = clf.fit(x_train, y_train).transform(x_train)


In [30]:
X_r2.shape

(8000, 1)

In [26]:
predictions_lda = clf_fit.predict(x_train)

In [31]:
import matplotlib.pyplot as plt
colors = ['navy', 'turquoise']
target_names = ["Yes","No"]

for color, i, target_name in zip(colors, [0, 1], target_names):
    plt.scatter(X_r2[y == , 0], X_r2[y == "No", 1], alpha=.8, color=color,
                label=target_name)
plt.legend(loc='best', shadow=False, scatterpoints=1)
plt.title('LDA of IRIS dataset')

plt.show()

/usr/local/lib/python3.6/site-packages/pandas/core/ops.py:798: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = getattr(x, name)(y)


TypeError: invalid type comparison

In [25]:
clf_qda = qda()
clf_qda_fit = clf_qda.fit(x_train,y_train)
predictions_qda = clf_qda.predict(x_train)

In [15]:
from sklearn.metrics import confusion_matrix 
confuse = confusion_matrix(y_train,predictions_nb)
print(confuse)

print("\nTN =",confuse[0][0])
print("FP =",confuse[0][1])
print("FN =",confuse[1][0])
print("TP =",confuse[1][1])

[[7715   28]
 [ 202   55]]

TN = 7715
FP = 28
FN = 202
TP = 55


In [16]:
from sklearn.metrics import confusion_matrix 
confuse = confusion_matrix(y_train,predictions_lda)
print(confuse)

print("\nTN =",confuse[0][0])
print("FP =",confuse[0][1])
print("FN =",confuse[1][0])
print("TP =",confuse[1][1])


[[7728   15]
 [ 200   57]]

TN = 7728
FP = 15
FN = 200
TP = 57


In [26]:
from sklearn.metrics import confusion_matrix 
confuse = confusion_matrix(y_train,predictions_qda)
print(confuse)

print("\nTN =",confuse[0][0])
print("FP =",confuse[0][1])
print("FN =",confuse[1][0])
print("TP =",confuse[1][1])

[[7725   18]
 [ 198   59]]

TN = 7725
FP = 18
FN = 198
TP = 59


In [30]:
clf_qda_fit.get_params()

{'priors': None, 'reg_param': 0.0, 'store_covariances': False, 'tol': 0.0001}

In [14]:
#overall accuracy
accuracy = (confuse[0][0] + confuse[1][1])/ len(y_test)
print("accuracy of classifier is:",accuracy)
#precision is a measure of positive predictions negative or ratio of tp/overal p
precision =  confuse[1][1]/(confuse[1][1]+confuse[0][1])
print("precision:",precision)
#recall is proportion all true positive samples.
recall = confuse[1][1]/(confuse[1][1]+confuse[1][0])
print("recall:",recall)

accuracy of classifier is: 0.975
precision: 0.75
recall: 0.25


In [15]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

             precision    recall  f1-score   support

          0       0.98      1.00      0.99      1940
          1       0.75      0.25      0.38        60

avg / total       0.97      0.97      0.97      2000



In [21]:
probs_positive_class = clf_fit.predict_proba(x_test)[:, 1]
probs_positive_class

results = []
for i in probs_positive_class:
    if i > 0.1:
        i = 1
        results.append(i)    
    else:
        i = 0
        results.append(i)
#print(results)

print(classification_report(y_test,results))

             precision    recall  f1-score   support

          0       0.99      0.94      0.96      1940
          1       0.28      0.78      0.41        60

avg / total       0.97      0.93      0.95      2000



In [22]:
confuse_new = confusion_matrix(y_test,results)
print(confuse_new)

print("\nTN =",confuse_new[0][0])
print("FP =",confuse_new[0][1])
print("FN =",confuse_new[1][0])
print("TP =",confuse_new[1][1])

[[1819  121]
 [  13   47]]

TN = 1819
FP = 121
FN = 13
TP = 47


In [23]:
# QDA
qda = QDA()
qda_fit = qda.fit(x_train, y_train, store_covariances=True)
y_pred_qda = qda_fit.predict(x_test)

/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:656: DeprecationWarning: The parameter 'store_covariances' is deprecated as of version 0.17 and will be removed in 0.19. The parameter is no longer necessary because the value is set via the estimator initialisation or set_params method.
  "set_params method.", DeprecationWarning)
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:695: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:719: RuntimeWarning: divide by zero encountered in power
  X2 = np.dot(Xm, R * (S ** (-0.5)))
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:719: RuntimeWarning: invalid value encountered in multiply
  X2 = np.dot(Xm, R * (S ** (-0.5)))
/usr/local/lib/python3.6/site-packages/sklearn/discriminant_analysis.py:722: RuntimeWarning: divide by zero encountered in log
  u = np.asarray([np.sum(np.

In [24]:
confuse_qda = confusion_matrix(y_test,y_pred_qda)
print(confuse_qda)

print("\nTN =",confuse_qda[0][0])
print("FP =",confuse_qda[0][1])
print("FN =",confuse_qda[1][0])
print("TP =",confuse_qda[1][1])

[[1940    0]
 [  60    0]]

TN = 1940
FP = 0
FN = 60
TP = 0


In [25]:
print(classification_report(y_test,y_pred_qda))

             precision    recall  f1-score   support

          0       0.97      1.00      0.98      1940
          1       0.00      0.00      0.00        60

avg / total       0.94      0.97      0.96      2000



/usr/local/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [50]:
results_qda = []
probs_positive_class_qda = qda_fit.predict_proba(x_test)[:, 1]
for i in probs_positive_class_qda:
    if i > 0.2:
        i = 1
        results_qda.append(i)    
    else:
        i = 0
        results_qda.append(i)
#print(results)

In [51]:
print(classification_report(y_test,results_qda))

             precision    recall  f1-score   support

          0       0.98      0.97      0.97      1932
          1       0.36      0.53      0.43        68

avg / total       0.96      0.95      0.96      2000



In [52]:
# plot data
import matplotlib.pyplot as plt
import matplotlib as mpl
from matplotlib import colors

def plot_data(lda, X, y, y_pred, fig_index):
    splot = plt.subplot(2, 2, fig_index)
    if fig_index == 1:
        plt.title('Linear Discriminant Analysis')
        plt.ylabel('Data with fixed covariance')
    elif fig_index == 2:
        plt.title('Quadratic Discriminant Analysis')
    elif fig_index == 3:
        plt.ylabel('Data with varying covariances')

    tp = (y_test == y_pred)  # True Positive
    tp0, tp1 = tp[y_test == 0], tp[y_test == 1]
    X0, X1 = x_test[y == 0], x_test[y == 1]
    X0_tp, X0_fp = X0[tp0], X0[~tp0]
    X1_tp, X1_fp = X1[tp1], X1[~tp1]
    xmin, xmax = x_test[:, 0].min(), x_test[:, 0].max()
    ymin, ymax = x_test[:, 1].min(), x_test[:, 1].max()

    # class 0: dots
    plt.plot(X0_tp[:, 0], X0_tp[:, 1], 'o', color='red')
    plt.plot(X0_fp[:, 0], X0_fp[:, 1], '.', color='#990000')  # dark red

    # class 1: dots
    plt.plot(X1_tp[:, 0], X1_tp[:, 1], 'o', color='blue')
    plt.plot(X1_fp[:, 0], X1_fp[:, 1], '.', color='#000099')  # dark blue

    # class 0 and 1 : areas
    nx, ny = 200, 100
    x_min, x_max = plt.xlim()
    y_min, y_max = plt.ylim()
    xx, yy = np.meshgrid(np.linspace(x_min, x_max, nx),
                         np.linspace(y_min, y_max, ny))
    Z = lda.predict_proba(np.c_[xx.ravel(), yy.ravel()])
    Z = Z[:, 1].reshape(xx.shape)
    plt.pcolormesh(xx, yy, Z, cmap='red_blue_classes',
                   norm=colors.Normalize(0., 1.))
    plt.contour(xx, yy, Z, [0.5], linewidths=2., colors='k')

    # means
    plt.plot(lda.means_[0][0], lda.means_[0][1],
             'o', color='black', markersize=10)
    plt.plot(lda.means_[1][0], lda.means_[1][1],
             'o', color='black', markersize=10)

    return splot

In [1]:
#plot_data(lda,x_test,y_test,y_pred,fig_index=2)

In [9]:
from sklearn import datasets

iris = datasets.load_iris()

X = iris.data
y = iris.target
target_names = iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')